[build]
builder = "RAILPACK"
buildCommand = "npx prisma generate && npm run build"

[deploy]
preDeployCommand = "npm run deployment:predeploy"
startCommand = "HOSTNAME=0.0.0.0 npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ALWAYS"