import { OrderStatus, ReturnRequestStatus, SupportCasePriority, SupportCaseStatus } from "@prisma/client";
import Link from "next/link";
import { AlertTriangle, FolderKanban, MessagesSquare, PackageSearch, RotateCcw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { StatCard } from "@/components/ui/stat-card";
import { adminUpdateOrderStatusAction, closeCustomerThreadAction, updateReturnIssueAction } from "@/app/admin/actions";
import { prisma } from "@/lib/db";
import { compactNumber, shortDate } from "@/lib/format";
import { requirePlatformPermission } from "@/lib/platform-admin";

export const dynamic = "force-dynamic";

type SupportPageProps = { searchParams?: Promise<{ error?: string }> };

export default async function SupportPage({ searchParams }: SupportPageProps) {
  const params = (await searchParams) ?? {};
  await requirePlatformPermission("support");
  const staleOrderDate = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const [returnIssues, openThreads, stuckOrders, failedMessages, openCases, urgentCases] = await Promise.all([
    prisma.returnRequest.findMany({ where: { status: { in: [ReturnRequestStatus.REQUESTED, ReturnRequestStatus.APPROVED, ReturnRequestStatus.RECEIVED] } }, include: { shop: true, order: true, buyer: true }, orderBy: { requestedAt: "desc" }, take: 30 }),
    prisma.customerThread.findMany({ where: { status: { not: "RESOLVED" } }, include: { shop: true, customer: true, messages: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" }, take: 30 }),
    prisma.order.findMany({ where: { status: { in: [OrderStatus.PENDING, OrderStatus.IN_PRODUCTION] }, createdAt: { lte: staleOrderDate } }, include: { shop: true, customer: true }, orderBy: { createdAt: "asc" }, take: 30 }),
    prisma.customerMessage.count({ where: { status: "FAILED" } }),
    prisma.supportCase.count({ where: { status: { notIn: [SupportCaseStatus.RESOLVED, SupportCaseStatus.CLOSED] } } }),
    prisma.supportCase.count({ where: { priority: SupportCasePriority.URGENT, status: { notIn: [SupportCaseStatus.RESOLVED, SupportCaseStatus.CLOSED] } } }),
  ]);

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-700">Customer operations</p><h1 className="mt-2 text-3xl font-semibold">Support desk</h1><p className="mt-2 text-sm text-slate-600">Command centre for live queues, platform evidence and durable investigation cases.</p></div><div className="flex flex-wrap gap-2"><Link className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold" href="/admin/investigate"><Search size={17} /> Investigate</Link><Link className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-semibold text-white" href="/admin/support/cases"><FolderKanban size={17} /> Case register</Link></div></div>
      {params.error ? <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">The support update was not applied. The record may have changed, require a refund workflow, or contain invalid data.</div> : null}

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="Open cases" value={compactNumber(openCases)} icon={<FolderKanban size={20} />} /><StatCard label="Urgent cases" value={compactNumber(urgentCases)} icon={<AlertTriangle size={20} />} /><StatCard label="Active returns" value={compactNumber(returnIssues.length)} icon={<RotateCcw size={20} />} /><StatCard label="Open conversations" value={compactNumber(openThreads.length)} icon={<MessagesSquare size={20} />} /><StatCard label="Delayed orders" value={compactNumber(stuckOrders.length)} icon={<PackageSearch size={20} />} /><StatCard label="Failed messages" value={compactNumber(failedMessages)} icon={<AlertTriangle size={20} />} /></section>

      <section className="grid gap-4 md:grid-cols-3"><Link href="/admin/investigate" className="panel p-5 transition hover:border-[#0f766e]"><Search size={20} /><h2 className="mt-3 text-xl font-semibold">Search platform evidence</h2><p className="mt-2 text-sm leading-6 text-slate-500">Find shops, Login IDs, suppliers, orders, payment references, messages and audit events.</p></Link><Link href="/admin/support/cases/new" className="panel p-5 transition hover:border-[#0f766e]"><FolderKanban size={20} /><h2 className="mt-3 text-xl font-semibold">Open an investigation</h2><p className="mt-2 text-sm leading-6 text-slate-500">Create a durable case with assignment, priority, notes and resolution history.</p></Link><Link href="/admin/support/cases" className="panel p-5 transition hover:border-[#0f766e]"><AlertTriangle size={20} /><h2 className="mt-3 text-xl font-semibold">Manage active cases</h2><p className="mt-2 text-sm leading-6 text-slate-500">Review urgent, unassigned, waiting and resolved cases in one register.</p></Link></section>

      <section className="panel overflow-hidden"><div className="border-b border-[#ded8cd] p-5"><h2 className="text-xl font-semibold">Return requests</h2><p className="mt-1 text-sm text-slate-500">Move non-financial return cases through approved operational states. Refunds and exchanges use their dedicated stock and payment workflows.</p></div><div className="divide-y divide-[#ded8cd] bg-white">{returnIssues.map((issue) => <article key={issue.id} className="grid gap-3 p-4 text-sm lg:grid-cols-[1fr_340px]"><div><p className="font-semibold">{issue.reason}</p><p className="mt-1 text-slate-500">{issue.shop.name} · {issue.order.receiptNumber} · {issue.buyer?.name ?? "Buyer"}</p><p className="mt-1 text-xs text-slate-400">Requested {shortDate(issue.requestedAt)}</p><Link className="mt-2 inline-flex text-xs font-semibold text-slate-600 hover:underline" href={`/admin/support/cases/new?shopId=${issue.shopId}&linkedEntityType=ReturnRequest&linkedEntityId=${issue.id}`}>Open durable case</Link></div><form action={updateReturnIssueAction} className="grid grid-cols-[1fr_auto] gap-2"><input type="hidden" name="returnRequestId" value={issue.id} /><select className="field min-h-9 py-1 text-xs" name="status" defaultValue={issue.status}>{Object.values(ReturnRequestStatus).map((status) => <option key={status} value={status}>{status}</option>)}</select><Button className="min-h-9 px-3 py-1 text-xs">Update</Button><input className="field col-span-2 min-h-9 py-1 text-xs" name="resolution" placeholder="Resolution note" /></form></article>)}{!returnIssues.length ? <p className="p-5 text-sm text-slate-500">No active return requests.</p> : null}</div></section>

      <section className="grid gap-5 xl:grid-cols-2">
        <div className="panel overflow-hidden"><div className="border-b border-[#ded8cd] p-5"><h2 className="text-xl font-semibold">Customer conversations</h2><p className="mt-1 text-sm text-slate-500">Unresolved communication threads requiring platform attention.</p></div><div className="divide-y divide-[#ded8cd] bg-white">{openThreads.map((thread) => <article key={thread.id} className="grid gap-3 p-4 text-sm sm:grid-cols-[1fr_auto]"><div><p className="font-semibold">{thread.subject}</p><p className="mt-1 text-slate-500">{thread.shop.name} · {thread.customer?.name ?? "Customer"}</p><p className="mt-2 line-clamp-2 text-xs text-slate-500">{thread.messages[0]?.body ?? "No message"}</p><Link className="mt-2 inline-flex text-xs font-semibold text-slate-600 hover:underline" href={`/admin/support/cases/new?shopId=${thread.shopId}&linkedEntityType=CustomerThread&linkedEntityId=${thread.id}`}>Open durable case</Link></div><form action={closeCustomerThreadAction}><input type="hidden" name="threadId" value={thread.id} /><Button variant="outline" className="min-h-9 px-3 py-1 text-xs">Resolve</Button></form></article>)}{!openThreads.length ? <p className="p-5 text-sm text-slate-500">No unresolved customer conversations.</p> : null}</div></div>
        <div className="panel overflow-hidden"><div className="border-b border-[#ded8cd] p-5"><h2 className="text-xl font-semibold">Delayed orders</h2><p className="mt-1 text-sm text-slate-500">Pending or in-production orders older than 24 hours.</p></div><div className="divide-y divide-[#ded8cd] bg-white">{stuckOrders.map((order) => <article key={order.id} className="p-4 text-sm"><div><p className="font-semibold">{order.receiptNumber}</p><p className="mt-1 text-slate-500">{order.shop.name} · {order.customer?.name ?? "No customer"} · {shortDate(order.createdAt)}</p><Link className="mt-2 inline-flex text-xs font-semibold text-slate-600 hover:underline" href={`/admin/support/cases/new?shopId=${order.shopId}&linkedEntityType=Order&linkedEntityId=${order.id}`}>Open durable case</Link></div><form action={adminUpdateOrderStatusAction} className="mt-3 grid grid-cols-[1fr_auto] gap-2"><input type="hidden" name="orderId" value={order.id} /><select className="field min-h-9 py-1 text-xs" name="status" defaultValue={order.status}>{Object.values(OrderStatus).map((status) => <option key={status} value={status}>{status}</option>)}</select><Button className="min-h-9 px-3 py-1 text-xs">Save</Button><input className="field col-span-2 min-h-9 py-1 text-xs" name="notes" placeholder="Admin note or cancellation reason" /></form></article>)}{!stuckOrders.length ? <p className="p-5 text-sm text-slate-500">No delayed orders currently require platform attention.</p> : null}</div></div>
      </section>
    </div>
  );
}
