CREATE TABLE "PlatformGovernanceSettings" (
    "id" TEXT NOT NULL DEFAULT 'platform',
    "platformName" TEXT NOT NULL DEFAULT 'Eugene Jersey Management',
    "legalCompanyName" TEXT,
    "supportEmail" TEXT,
    "supportPhone" TEXT,
    "defaultCountry" TEXT NOT NULL DEFAULT 'Ghana',
    "defaultCurrency" TEXT NOT NULL DEFAULT 'GHS',
    "defaultTimezone" TEXT NOT NULL DEFAULT 'Africa/Accra',
    "termsVersion" TEXT,
    "privacyVersion" TEXT,
    "marketplaceEnabled" BOOLEAN NOT NULL DEFAULT true,
    "publicApplicationsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
    "incidentMode" BOOLEAN NOT NULL DEFAULT false,
    "paymentsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "messagingEnabled" BOOLEAN NOT NULL DEFAULT true,
    "signupsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "maintenanceNotice" TEXT,
    "trialDays" INTEGER NOT NULL DEFAULT 14,
    "includedStaffAccounts" INTEGER NOT NULL DEFAULT 3,
    "supportSlaHours" INTEGER NOT NULL DEFAULT 24,
    "loginAttemptLimit" INTEGER NOT NULL DEFAULT 5,
    "sessionLifetimeMinutes" INTEGER NOT NULL DEFAULT 10080,
    "sensitiveActionReauthMinutes" INTEGER NOT NULL DEFAULT 15,
    "auditRetentionDays" INTEGER NOT NULL DEFAULT 2555,
    "dataRetentionDays" INTEGER NOT NULL DEFAULT 2555,
    "allowedUploadTypes" TEXT[] NOT NULL DEFAULT ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml', 'application/pdf']::TEXT[],
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "PlatformGovernanceSettings_pkey" PRIMARY KEY ("id")
);
